# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_1d_data": "custom_pytorch_training.ipynb",
         "generate_2d_data": "custom_pytorch_training.ipynb",
         "train": "custom_pytorch_training.ipynb",
         "eval_loss": "custom_pytorch_training.ipynb",
         "train_epochs": "custom_pytorch_training.ipynb",
         "Histogram": "custom_pytorch_training.ipynb",
         "MixtureOfLogistics": "custom_pytorch_training.ipynb",
         "MNISTDataGenerator": "data_generator.ipynb",
         "KerasPipeline": "function_approximation.ipynb",
         "HighLevelKerasPipeline": "function_approximation.ipynb",
         "HighLevelKerasPipelineMultiTarget": "function_approximation.ipynb",
         "download_keras_data": "transformers.ipynb",
         "unicode_to_ascii": "transformers.ipynb",
         "preprocess_sentence": "transformers.ipynb",
         "create_attention_dataset": "transformers.ipynb",
         "tokenize": "transformers.ipynb",
         "load_attention_dataset": "transformers.ipynb",
         "Encoder": "transformers.ipynb",
         "BahdanauAttention": "transformers.ipynb",
         "Decoder": "transformers.ipynb"}

modules = ["custom_pytorch_training.py",
           "custom_tf_training.py",
           "data_generator.py",
           "function_approximation.py",
           "transformers.py"]

doc_url = "https://jovsa.github.io/jovsatools/"

git_url = "https://github.com/jovsa/jovsatools/tree/master/"

def custom_doc_links(name): return None
