# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/roc.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
%load_ext autoreload
%autoreload 2
from nbdev.showdoc import *
import jovsatools
import fastcore
import sklearn

# Cell
def say_hello(name):
    print(f'hi there: {name}')