# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/billy_bean.ipynb (unless otherwise specified).

__all__ = []

# Cell
%load_ext autoreload
%autoreload 2
from nbdev.showdoc import *
import jovsatools
import fastcore
from .billy_bean import git

# Cell
git.temp()