# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/custering_and_neighbours.ipynb (unless otherwise specified).

__all__ = []

# Cell
from nbdev.showdoc import *
import jovsatools
import fastcore
from sklearn.datasets import make_blobs
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from collections import defaultdict