# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/customizing_tf_fit.ipynb (unless otherwise specified).

__all__ = []

# Cell
from nbdev.showdoc import *
import jovsatools
import fastcore
import tensorflow as tf
from tensorflow import keras
import numpy as np