# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/minitorch.ipynb (unless otherwise specified).

__all__ = []

# Cell
from nbdev.showdoc import *
import jovsatools
from .minitorch import minitorch
import fastcore

# Cell
dir(minitorch)