# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/mote_carlo_eth2.ipynb (unless otherwise specified).

__all__ = []

# Cell
from nbdev.showdoc import *
import jovsatools
import fastcore
import numpy as np
from collections import Counter, defaultdict
from tqdm import tqdm
import seaborn as sns
from typing import Optional, List
import pandas as pd
import matplotlib.pyplot as plt

# Cell
stats.plot.box()
plt.rcParams['figure.figsize'] = [30, 10]

# Cell
stats.describe()