# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/roc.ipynb (unless otherwise specified).

__all__ = []

# Cell
from nbdev.showdoc import *
import jovsatools
import fastcore
import sklearn

import numpy as np
np.random.seed(10)

import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (RandomTreesEmbedding, RandomForestClassifier,
                              GradientBoostingClassifier)
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.pipeline import make_pipeline