# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"train": "custom_pytorch_training.ipynb",
         "eval_loss": "custom_pytorch_training.ipynb",
         "train_epochs": "custom_pytorch_training.ipynb"}

modules = ["custom_pytorch_training.py"]

doc_url = "https://jovsa.github.io/jsmltools/"

git_url = "https://github.com/jovsa/jsmltools/tree/master/"

def custom_doc_links(name): return None
