# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["hello_nbdev.py"]

doc_url = "https://jovsa.github.io/jsmltools/"

git_url = "https://github.com/jovsa/jsmltools/tree/master/"

def custom_doc_links(name): return None
